ENCODING = 'utf-8'
EMAIL_PROVIDER = 'srv.email_provider'
WTI_DYNAMIC_CONTENT = 'srv.wti_dynamic_content'
ZENDESK_DC = 'srv.zendesk_dynamic_content'
APP_SETTINGS = 'settings'
SLACK_NOTIFIER = 'srv.slack'
STATS = 'srv.stats'
